
services:
  - type: web
    name: laravel12-app
    env: docker
    plan: free
    repo: "https://github.com/fer-privacy/prueva_final_laravel.git"
    region: oregon
    buildCommand: "echo 'Dockerfile already handles build'"
    startCommand: "echo 'Dockerfile already handles start'"
